# Generated by Django 4.2.3 on 2023-07-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
