# Generated by Django 4.2.3 on 2023-07-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_delete_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "User field",
                "verbose_name_plural": "User fields",
            },
        ),
    ]
