# Generated by Django 4.2.3 on 2023-07-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message"),
        ("userauth", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="manager_chat",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="chats.chat"
            ),
        ),
    ]
